# Generated by Django 4.2 on 2023-04-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoAGA', '0002_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoacceso',
            name='borrado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='puntoacceso',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
