# Generated by Django 4.2 on 2023-04-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoAGA', '0003_alter_puntoacceso_borrado_alter_puntoacceso_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoacceso',
            name='estado',
            field=models.CharField(choices=[(1, 'ACTIVO'), (0, 'ACTIVO')], default=1, max_length=5),
        ),
    ]
