# Generated by Django 4.2 on 2023-04-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoAGA', '0004_alter_puntoacceso_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoacceso',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default=1, max_length=5),
        ),
        migrations.AlterField(
            model_name='puntoacceso',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
