# Generated by Django 4.1.7 on 2023-04-11 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoAGA', '0005_alter_puntoacceso_estado_alter_puntoacceso_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=200)),
                ('area_servicio', models.CharField(max_length=200)),
                ('fecha_inicio_actividad', models.DateField(default=datetime.date.today)),
                ('fecha_fin_actividad', models.DateField(default=datetime.date.today)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default=1, max_length=5)),
                ('borrado', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
