# Generated by Django 4.1.7 on 2023-04-14 14:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoAGA', '0007_alter_usuario_borrado_alter_usuario_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=100)),
                ('nomre_completo', models.CharField(max_length=200)),
                ('fecha_inicio_actividad', models.DateField(default=datetime.date.today)),
                ('fecha_fin_actividad', models.DateField(default=datetime.date.today)),
                ('observaciones', models.TextField(max_length=300)),
                ('tipo_persona', models.CharField(choices=[('1', 'Trabajador'), ('2', 'Proveedor'), ('3', 'Visitante'), ('4', 'Contratista')], max_length=5)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default=1, max_length=5)),
                ('borrado', models.BooleanField(blank=True, default=False, null=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppProyectoAGA.empresa')),
                ('portal_autorizado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppProyectoAGA.puntoacceso')),
            ],
        ),
    ]
