# Generated by Django 4.1.7 on 2023-04-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoAGA', '0008_personal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='nomre_completo',
            new_name='nomrbe_completo',
        ),
    ]
