# Generated by Django 4.1.7 on 2023-04-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoAGA', '0009_rename_nomre_completo_personal_nomrbe_completo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='nomrbe_completo',
            new_name='nombre_completo',
        ),
    ]
