# Generated by Django 4.1.7 on 2023-04-14 18:17

import AppProyectoAGA.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoAGA', '0010_rename_nomrbe_completo_personal_nombre_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='foto',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to=AppProyectoAGA.models.guardar_imagen_personal, verbose_name='Imagen del personal'),
        ),
    ]
