# Generated by Django 4.1.7 on 2023-04-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoAGA', '0011_personal_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='observaciones',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
