# Generated by Django 4.1.7 on 2023-04-25 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoAGA', '0017_alter_acceso_fecha_ingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceso',
            name='empresa',
        ),
        migrations.AlterField(
            model_name='acceso',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 9, 18, 4, 463147)),
        ),
    ]
