# Generated by Django 4.1.7 on 2023-04-25 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoAGA', '0018_remove_acceso_empresa_alter_acceso_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceso',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 10, 52, 16, 159669)),
        ),
        migrations.AlterField(
            model_name='acceso',
            name='ingreso',
            field=models.CharField(choices=[('1', 'Personal'), ('2', 'Vehiculo')], max_length=5),
        ),
    ]
