# Generated by Django 4.1.7 on 2023-04-25 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoAGA', '0019_alter_acceso_fecha_ingreso_alter_acceso_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceso',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 12, 9, 48, 877659)),
        ),
        migrations.AlterField(
            model_name='personal',
            name='documento',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterModelTable(
            name='personal',
            table='personal',
        ),
        migrations.AlterModelTable(
            name='vehiculo',
            table='vehiculos',
        ),
    ]
