# Generated by Django 4.1.7 on 2023-04-25 18:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoAGA', '0020_alter_acceso_fecha_ingreso_alter_personal_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceso',
            name='portal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppProyectoAGA.puntoacceso'),
        ),
        migrations.AlterField(
            model_name='acceso',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 13, 35, 51, 576072)),
        ),
    ]
