# Generated by Django 4.1.7 on 2023-04-28 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoAGA', '0021_acceso_portal_alter_acceso_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceso',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acceso',
            name='tipo',
            field=models.CharField(choices=[('1', 'Entrada'), ('2', 'Salida')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='acceso',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 13, 7, 50, 535456)),
        ),
    ]
