# Generated by Django 4.1.7 on 2023-04-28 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoAGA', '0022_acceso_fecha_salida_acceso_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceso',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 15, 43, 25, 592087)),
        ),
        migrations.AlterModelTable(
            name='acceso',
            table='accesos',
        ),
        migrations.AlterModelTable(
            name='empresa',
            table='empresas',
        ),
        migrations.AlterModelTable(
            name='puntoacceso',
            table='puntos_de_acceso',
        ),
    ]
