# Generated by Django 4.1.7 on 2023-04-28 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoAGA', '0023_alter_acceso_fecha_ingreso_alter_acceso_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceso',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 15, 43, 59, 17772)),
        ),
        migrations.AlterModelTable(
            name='permiso',
            table='permisos',
        ),
    ]
