# Generated by Django 4.1.7 on 2023-04-28 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoAGA', '0024_alter_acceso_fecha_ingreso_alter_permiso_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceso',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 28, 17, 20, 25, 643936)),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nit',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
