# Generated by Django 4.1.7 on 2023-05-05 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoAGA', '0026_alter_acceso_fecha_ingreso_alter_personal_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceso',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 7, 23, 25, 26667)),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='codigo',
            field=models.CharField(max_length=200),
        ),
    ]
