# Generated by Django 4.1.7 on 2023-05-09 05:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoAGA', '0031_alter_acceso_fecha_ingreso_alter_personal_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceso',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 0, 2, 45, 814399)),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nit',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='personal',
            name='documento',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
    ]
