# Generated by Django 4.1.7 on 2023-05-09 12:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoAGA', '0032_alter_acceso_fecha_ingreso_alter_empresa_nit_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='permiso',
            name='unique_codigo_activo',
        ),
        migrations.AlterField(
            model_name='acceso',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 7, 38, 37, 103907)),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nit',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='personal',
            name='documento',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.BigIntegerField(validators=[django.core.validators.MinLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name='empresa',
            constraint=models.UniqueConstraint(condition=models.Q(('borrado', False)), fields=('nit',), name='unique_nitEmpresa_activo'),
        ),
        migrations.AddConstraint(
            model_name='permiso',
            constraint=models.UniqueConstraint(condition=models.Q(('borrado', False)), fields=('codigo',), name='unique_codigoPermiso_activo'),
        ),
        migrations.AddConstraint(
            model_name='personal',
            constraint=models.UniqueConstraint(condition=models.Q(('borrado', False)), fields=('documento',), name='unique_documentoPersonal_activo'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(condition=models.Q(('borrado', False)), fields=('documento',), name='unique_documentoUsuario_activo'),
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.UniqueConstraint(condition=models.Q(('borrado', False)), fields=('placa',), name='unique_placaVehiculo_activo'),
        ),
    ]
